create table if not exists employee_leave_balance (
    id bigint generated by default as identity primary key,
    employee_name varchar(64) not null unique,
    annual_leave_balance integer not null,
    sick_leave_balance integer not null
);

create table if not exists leave_application (
    id bigint generated by default as identity primary key,
    apply_no varchar(32) not null unique,
    employee_name varchar(64) not null,
    leave_type varchar(32) not null,
    start_time timestamp not null,
    end_time timestamp not null,
    reason varchar(500) not null,
    status varchar(32) not null,
    created_at timestamp not null
);

create table if not exists attendance_record (
    id bigint generated by default as identity primary key,
    employee_name varchar(64) not null,
    attendance_date date not null,
    check_in_time time,
    check_out_time time,
    status varchar(32) not null,
    remark varchar(500),
    unique (employee_name, attendance_date)
);

create table if not exists candidate (
    id bigint generated by default as identity primary key,
    name varchar(64) not null,
    position varchar(128) not null,
    years integer not null,
    skills varchar(500) not null,
    status varchar(32) not null,
    phone varchar(32) not null,
    email varchar(128) not null
);

alter table candidate add column if not exists skills varchar(500);

create table if not exists interview_schedule (
    id bigint generated by default as identity primary key,
    interview_no varchar(32) not null unique,
    candidate_name varchar(64) not null,
    interviewer_name varchar(64) not null,
    interview_time timestamp not null,
    round varchar(32) not null,
    mode varchar(32) not null,
    status varchar(32) not null,
    created_at timestamp not null
);

create table if not exists user_account (
    id bigint generated by default as identity primary key,
    username varchar(64) not null unique,
    password_hash varchar(128) not null,
    employee_name varchar(64) not null,
    role varchar(32) not null,
    enabled boolean not null
);

create table if not exists ai_workflow_run (
    id bigint generated by default as identity primary key,
    workflow_id varchar(64) not null unique,
    workflow_type varchar(64) not null,
    employee_name varchar(64) not null,
    message varchar(1000) not null,
    intent varchar(64),
    status varchar(32) not null,
    result_summary varchar(1000),
    started_at timestamp not null,
    finished_at timestamp not null
);

create table if not exists ai_workflow_step_log (
    id bigint generated by default as identity primary key,
    workflow_id varchar(64) not null,
    step_order integer not null,
    step_name varchar(64) not null,
    status varchar(32) not null,
    message varchar(1000) not null,
    executed_at timestamp not null
);

create table if not exists mcp_tool_audit_log (
    id bigint generated by default as identity primary key,
    trace_id varchar(64) not null,
    tool_name varchar(64) not null,
    tenant_id varchar(64),
    user_id bigint,
    session_id varchar(128),
    pending_id varchar(64),
    status varchar(32) not null,
    error_code varchar(64),
    duration_ms bigint not null,
    argument_summary varchar(2000) not null,
    created_at timestamp not null
);
